<?php

declare(strict_types=1);

/**
 * @author      Andreas Knollmann
 * @copyright   Copyright (c) 2014-2024 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */

use Infrangible\CatalogAttributeLandingPage\Block\Group;
/** @var Group $block */
$description = $block->getDescription();
?>

<?php if ($description): ?>
    <div class="landing-page-description category-description std"><?php echo $description; ?></div>
<?php endif; ?>

<?php echo $block->getCmsBlockHtml(); ?>

<?php echo $block->getGroupedPagesHtml(); ?>
