<?php

declare(strict_types=1);

/**
 * @author      Andreas Knollmann
 * @copyright   Copyright (c) 2014-2024 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */

use Infrangible\CatalogAttributeLandingPage\Block\Page;

/** @var Page $block */
$image = $block->getPage()->getImage();
$imagePosition = $block->getImagePosition();
$cmsBlockHtml = $block->getCmsBlockHtml();
$additionalCmsBlockHtml = $block->getAdditionalCmsBlockHtml();
?>

<?php if ($image && $imagePosition === 'cms'): ?>
    <div class="category-image"><img src="<?php echo $block->getPage()->getImageUrl(); ?>" alt="<?php echo $block->getHeadline(); ?>" title="<?php echo $block->getHeadline(); ?>" class="image"/></div>
<?php endif; ?>

<?php if ($cmsBlockHtml || $additionalCmsBlockHtml) :?>
    <div class="category-cms">
        <?php echo $cmsBlockHtml; ?>
        <?php echo $additionalCmsBlockHtml; ?>
    </div>
<?php endif; ?>
